openapi: 3.0.1
info:
  title: Demo API
  description: 'Demo api showing all kind of cool dotnet stuff, check it out at <a href="https://github.com/svrooij/demo-api-with-auth/">github</a> or let me know on <a href="https://www.linkedin.com/posts/stephanvanrooij_github-svrooijdemo-api-with-auth-a-demo-activity-7222324418478325760-2SGI?utm_source=share&utm_medium=member_desktop">LinkedIn</a> what you think.<br/><br/>Yes, I know, a weather forcast is boring, that is not the point.'
  termsOfService: https://github.com/svrooij/demo-api-with-auth?tab=readme-ov-file
  contact:
    name: Stephan van Rooij
    url: https://svrooij.io
  license:
    name: MIT
    url: https://github.com/svrooij/demo-api-with-auth?tab=MIT-1-ov-file
  version: v1
servers:
  - url: /
    description: Current server
paths:
  /weatherforecast:
    get:
      tags:
        - Weather
      summary: Get the weather forecast
      description: Get the weather forecast for the next 5 days
      operationId: GetWeatherForecast
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
        '401':
          description: Unauthorized
      security:
        - Bearer:
            - api://36f6d633-90b0-409e-81fa-e45e81f42fe1/access_as_user
            - openid
  /claims:
    get:
      tags:
        - User
      summary: Get the claims of the user
      description: Get the claims of the user that is currently logged in
      operationId: GetClaims
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '401':
          description: Unauthorized
      security:
        - Bearer:
            - api://36f6d633-90b0-409e-81fa-e45e81f42fe1/access_as_user
            - openid
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperatureC:
          type: integer
          format: int32
        summary:
          type: string
          nullable: true
        temperatureF:
          type: integer
          format: int32
          readOnly: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: oauth2
      description: JWT Authorization header using the Bearer scheme.
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes:
            openid: Default
            api://36f6d633-90b0-409e-81fa-e45e81f42fe1/access_as_user: API Access